In [ ]:
# Dataframe - Df - Special object on data type 'pandas' to store data in a tabular form

In [2]:
import pandas as pd
import numpy as np

### Dictionary to DataFrame Object

In [3]:
# We can convert the dictionary or a Numpy Array directly in the form of data frame object. 
#Eg - Consider the data of marks of 10 students in 3 subjects.
#(Data of marks has been generated randomly) as for now, we don't have any data 
user_data  = {
    'Chemistry': np.random.randint(1,100,10),
    'Maths': np.random.randint(1,100,10),
    'Physics' : np.random.randint(1,100,10)
}

In [4]:
print(type(user_data))

<class 'dict'>


In [6]:
user_data

{'Chemistry': array([87,  2, 83, 90, 31, 48, 96, 61, 52, 28]),
 'Maths': array([15, 66, 75, 60, 39, 33, 89, 88, 38, 79]),
 'Physics': array([39, 79, 97, 59, 92,  7, 95,  2, 89, 37])}

In [11]:
#Converting the dictionary directly into a data frame object like this --> Passing the dictionary in the constructor 
#of DataFrame class of pandas
df = pd.DataFrame(user_data)
df.head() 

Chemistry  Maths  Physics
0         87     15       39
1          2     66       79
2         83     75       97
3         90     60       59
4         31     39       92

In [14]:
# By default it prints only first 5 tuples, but if you want to print more or less , do like this
df.head(n=10)

Chemistry  Maths  Physics
0         87     15       39
1          2     66       79
2         83     75       97
3         90     60       59
4         31     39       92
5         48     33        7
6         96     89       95
7         61     88        2
8         52     38       89
9         28     79       37

In [66]:
#Clearly we can see that since we passed the data in the dictionary as INT, therefore in the dataframe object too 
#data was stored as int but if we want to store it as Float or some other data type , then we can explicity mention
df = pd.DataFrame(user_data,dtype='float32')
df.head(n=6)

Chemistry  Maths  Physics
0       87.0   15.0     39.0
1        2.0   66.0     79.0
2       83.0   75.0     97.0
3       90.0   60.0     59.0
4       31.0   39.0     92.0
5       48.0   33.0      7.0

In [19]:
#Like df.head gives tuples from top, df.tail gives tuples from bottom
df.tail(n=5)

Chemistry  Maths  Physics
5       48.0   33.0      7.0
6       96.0   89.0     95.0
7       61.0   88.0      2.0
8       52.0   38.0     89.0
9       28.0   79.0     37.0

In [17]:
#We can get all the names of the columns of a table in the dataFrame like this ->
columns = df.columns
print(type(columns))
print(columns)

<class 'pandas.core.indexes.base.Index'>
Index(['Chemistry', 'Maths', 'Physics'], dtype='object')


In [67]:
#Getting the whole column from the data frame object like this -->
marksInMaths = df.get('Maths')
print(type(marksInMaths)) ## A type of list is pandas , can be convertes to numpy list by typecasting
print(marksInMaths.shape)

<class 'pandas.core.series.Series'>
(10,)


In [68]:
print(marksInMaths)

0    15.0
1    66.0
2    75.0
3    60.0
4    39.0
5    33.0
6    89.0
7    88.0
8    38.0
9    79.0
Name: Maths, dtype: float32


In [69]:
print(np.array(marksInMaths))

[15. 66. 75. 60. 39. 33. 89. 88. 38. 79.]


In [25]:
## Accessing data in the data frame -->

print(df.iloc[3]) ##It will get all the data of the 3rd row
df.head(n=10)

Chemistry    90.0
Maths        60.0
Physics      59.0
Name: 3, dtype: float32


Chemistry  Maths  Physics
0       87.0   15.0     39.0
1        2.0   66.0     79.0
2       83.0   75.0     97.0
3       90.0   60.0     59.0
4       31.0   39.0     92.0
5       48.0   33.0      7.0
6       96.0   89.0     95.0
7       61.0   88.0      2.0
8       52.0   38.0     89.0
9       28.0   79.0     37.0

In [26]:
#These all work in the same way to access data at the 3rd index row and column index = 1
print(df.iloc[3][1])
print(df.iloc[3,1])
print(df.iloc[3]['Maths'])

60.0
60.0
60.0


In [30]:
#We can also get the index of multiple columns of a single row like this --> Like we want to get the data in 1st,2nd
#column in the 3rd row. Then you do this -->
columnsIndexesList = [1,2]
print(df.iloc[3,columnsIndexesList])

Maths      60.0
Physics    59.0
Name: 3, dtype: float32


In [35]:
#Getting the index of the column by the name of the column
idx = df.columns.get_loc('Maths')
print(type(idx))
print(idx)

<class 'int'>
1


In [36]:
##Slicing the dataFrame to get specific tuples

#Getting the data of first 5 tuples where data of only 1st and 2nd column index should be printed
df.iloc[:5,[1,2]] ##Data of 0th column is not printed

Maths  Physics
0   15.0     39.0
1   66.0     79.0
2   75.0     97.0
3   60.0     59.0
4   39.0     92.0

In [44]:
df.iloc[5:,0] ##Data of 0th column is not printed

5    48.0
6    96.0
7    61.0
8    52.0
9    28.0
Name: Chemistry, dtype: float32

In [45]:
df.iloc[5:,[0]] ##Data of 0th column is not printed

Chemistry
5       48.0
6       96.0
7       61.0
8       52.0
9       28.0

In [46]:
df.head(n=10)

Chemistry  Maths  Physics
0       87.0   15.0     39.0
1        2.0   66.0     79.0
2       83.0   75.0     97.0
3       90.0   60.0     59.0
4       31.0   39.0     92.0
5       48.0   33.0      7.0
6       96.0   89.0     95.0
7       61.0   88.0      2.0
8       52.0   38.0     89.0
9       28.0   79.0     37.0

In [48]:
##Sorting the dataframe on the basis of  marks in Chemistry
df.sort_values(by=['Chemistry'],ascending=False)

Chemistry  Maths  Physics
6       96.0   89.0     95.0
3       90.0   60.0     59.0
0       87.0   15.0     39.0
2       83.0   75.0     97.0
7       61.0   88.0      2.0
8       52.0   38.0     89.0
5       48.0   33.0      7.0
4       31.0   39.0     92.0
9       28.0   79.0     37.0
1        2.0   66.0     79.0

In [49]:
# Sorting the dataframe on the basis of  marks in Chemistry, and if marks are same in chemisty , then compare the marks
#in maths, then sort it seeing that
df.sort_values(by=['Chemistry','Maths'],ascending=False)

Chemistry  Maths  Physics
6       96.0   89.0     95.0
3       90.0   60.0     59.0
0       87.0   15.0     39.0
2       83.0   75.0     97.0
7       61.0   88.0      2.0
8       52.0   38.0     89.0
5       48.0   33.0      7.0
4       31.0   39.0     92.0
9       28.0   79.0     37.0
1        2.0   66.0     79.0

### Convert DataFrame Object directly into a numpy array

In [50]:
print(type(df))

#Converting the Dataframe object,  directly into a numpy array can be done like this
data_array = df.values
print(type(data_array))

<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>


In [53]:
print(data_array.shape)
print()
print(data_array)

(10, 3)

[[87. 15. 39.]
 [ 2. 66. 79.]
 [83. 75. 97.]
 [90. 60. 59.]
 [31. 39. 92.]
 [48. 33.  7.]
 [96. 89. 95.]
 [61. 88.  2.]
 [52. 38. 89.]
 [28. 79. 37.]]


### Converting a numpy array directly into a Dataframe Object where each row of numpy array will be tuple of DF

In [54]:
new_data_frame = pd.DataFrame(data_array,columns = ['SubjectA','SubjectB','SubjectC'])

new_data_frame.head(n=10)

SubjectA  SubjectB  SubjectC
0      87.0      15.0      39.0
1       2.0      66.0      79.0
2      83.0      75.0      97.0
3      90.0      60.0      59.0
4      31.0      39.0      92.0
5      48.0      33.0       7.0
6      96.0      89.0      95.0
7      61.0      88.0       2.0
8      52.0      38.0      89.0
9      28.0      79.0      37.0

In [55]:
#Instead of inserting the float(which is by default), let's make it int32 and and then insert
new_data_frame = pd.DataFrame(data_array,columns = ['SubjectA','SubjectB','SubjectC'],dtype='int32')
new_data_frame.head(n=10)

SubjectA  SubjectB  SubjectC
0        87        15        39
1         2        66        79
2        83        75        97
3        90        60        59
4        31        39        92
5        48        33         7
6        96        89        95
7        61        88         2
8        52        38        89
9        28        79        37

### Writing a Data Frame Object directly into a csv File -->

In [56]:
new_data_frame.to_csv("myNew.csv") 

In [57]:
#Reading a csv file and converting it directly to a data frame object
df = pd.read_csv('myNew.csv')
df.head()

Unnamed: 0  SubjectA  SubjectB  SubjectC
0           0        87        15        39
1           1         2        66        79
2           2        83        75        97
3           3        90        60        59
4           4        31        39        92

### Dropping a column in a Data Frame Object

In [60]:
df = df.drop(columns=['Unnamed: 0'])
df.head()

SubjectA  SubjectB  SubjectC
0        87        15        39
1         2        66        79
2        83        75        97
3        90        60        59
4        31        39        92

In [61]:
##When we write csv file like this, and additional column of index will be inserted as you can see it in the output. 
#Either you drop this columns as shown above for better visibility, or if we want while making the csv file . Then
#it should not be inserted in the csv file. You should create a csv file like this -->
df.to_csv("myNew2.csv",index = False)

In [62]:
df = pd.read_csv('myNew2.csv')
df.head() ##Therefore now it is not inserted

SubjectA  SubjectB  SubjectC
0        87        15        39
1         2        66        79
2        83        75        97
3        90        60        59
4        31        39        92

In [63]:
## Sometimes we make also need to analyse the data frame object, in that case there is a function describe which best 
#describe our data frame object
df.describe() ##Here std - standard deviation

SubjectA   SubjectB   SubjectC
count  10.000000  10.000000  10.000000
mean   57.800000  58.200000  59.600000
std    31.346806  25.589929  36.457586
min     2.000000  15.000000   2.000000
25%    35.250000  38.250000  37.500000
50%    56.500000  63.000000  69.000000
75%    86.000000  78.000000  91.250000
max    96.000000  89.000000  97.000000