In [61]:
#Numpty -  It is basically useful in linear algebra(matrix multiplication,transpose,etc), random number generator  etc.
import numpy as np

In [62]:
a = np.array([1,2,3,4,5]) #Always consider an array in numpy as a matrix only
print(a)
print(type(a))

print()

#Therefore above is a 5x1 matrix. Which we can calculate using shape property 
print(a.shape) #The array/matrix has 1 row and 5 columns. When we have only 1 row in the numpy array, then shape comes like this only
print(a[2])#Accessing an element at some index in the array


[1 2 3 4 5]
<class 'numpy.ndarray'>

(5,)
3


In [63]:
print(np.sum(a))

15


In [20]:
b = np.array([ [1], [2] , [3] , [4] , [5] ])
print(type(b))
print(b)

print()

print("Shape = ", b.shape) #Therefore it has 5 rows and 1 column. Therefore shape basically gives the dimensions of shape in the form of tuple
print(b[2][0])
#print(b[2][1])-> this is an error as in the 2nd row , we don't have any 1st index in column


<class 'numpy.ndarray'>
[[1]
 [2]
 [3]
 [4]
 [5]]

Shape =  (5, 1)
3


In [17]:
c = np.array([ 
    [1,2,3], 
    [4,5,6] 
])
print("Shape = ", c.shape)
print(c)

print()
print(c[1][1])

Shape =  (2, 3)
[[1 2 3]
 [4 5 6]]

5


In [24]:
#We can make a numpy array(or matrix) where all elements will be zeroes or all ones or some other constant
a = np.zeros((3,4)) #It will make an array(or matrix) of size 3x4 with all the elements initialized with 0
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [25]:
#an array initialised all elements with one
b = np.ones((2,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [26]:
#Initialising all the elements of the array with some constant
c = np.full((3,2),100)  #Therefore it makes a matrix of dimensions 3x2 with all elements initialised with 100
print(c)

[[100 100]
 [100 100]
 [100 100]]


In [27]:
#Now we should observe the data type of element initialised above
print(type(a[0][0])) #Or we can also get the data type of element in the matrix using (a.dtype) -> it is the same thing
print(type(b[0][0]))
print(type(c[0][0]))

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.int64'>


In [28]:
#Therefore when we initialize the array with zeroes or one, the default data type set of each element is a float. 
#But if we want, that it should be any other than float. Like we want to be an int. Then do like this ->
a = np.zeros((2,3),dtype=np.int64)
print(a)
b = np.ones((2,3),dtype=np.int64)
print(b)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]


In [85]:
#We can also make a 1d numpy array like this ->
a = np.arange(10)#Here each element will be equal to index i
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [86]:
a = np.arange(10)+5#Here each element will be equal to index i+5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


### Making Identity matrix in numpy

In [29]:
myIdentityMatrix = np.eye(5)# Identity matrix of size 5x5 as identity matrix are always sqaure
print(myIdentityMatrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [30]:
#again we make the dtype of the above identity matrix as int
myIdentityMatrix = np.eye(5,dtype=np.int64)
print(myIdentityMatrix)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [167]:
#See about how to calculate transpose, adding scalar to matrix and multiplying scalar to matrix from down in matrix 
#and tensor section

### Slicing in matrices(or Numpy Array)

In [32]:
myNumpyArray = np.array([
    [1,2,3,4],
    [2,4,6,20],
    [10,13,15,18]
])
print(myNumpyArray)

[[ 1  2  3  4]
 [ 2  4  6 20]
 [10 13 15 18]]


In [34]:
#Now get me all the elements of 2nd index column
print(myNumpyArray[:,2])

[ 3  6 15]


In [33]:
#Now what we want is all elements of 1st row starting from 1st index
print(myNumpyArray[1,1:])#Always returned in the form of list

[ 4  6 20]


In [35]:
#We can also update elements together of rows or columns
#E.g - Update the elements at 2nd row index(from column index = 1) as 1000
myNumpyArray[2,1:] = 1000
print(myNumpyArray)

[[   1    2    3    4]
 [   2    4    6   20]
 [  10 1000 1000 1000]]


In [36]:
#We can also set all the elements to a particular value using slicing like this.
myNumpyArray[:,:] = 0
print(myNumpyArray)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [37]:
#Now what i want is set all the values in column index = 2 to 19 (values to be updated only till 2nd last row)
myNumpyArray[:-1,2] = 19
print(myNumpyArray)

[[ 0  0 19  0]
 [ 0  0 19  0]
 [ 0  0  0  0]]


### Sum in numpy array.

In [65]:
myNumpyArray = np.array([
    [1,2,3,4],
    [2,4,6,20],
    [10,13,15,18]
])

print(np.sum(myNumpyArray)) #It calculates the sum of each element in the matrix

98


In [67]:
#Now what we want is get the sum column wise 
print(np.sum(myNumpyArray,axis=0))#Therefore clearly sum of elements in -->
# 1st Column - 13
# 2nd Column - 19
# 3rd Column - 24
# 4th Column - 42

[13 19 24 42]


In [68]:
#We can also get the sum row wise
print(np.sum(myNumpyArray,axis=1))

#Therefore axis = 0 is the vertical axis and when axis = 1, it corresponds to horizontal axis

[10 32 56]


### Stacking of arrays together

In [76]:
a = np.array([1,2,3,4])

b = np.array([5,6,7,8])

#Stacking means joinging 2 numpy arrays together to form a new numpy array of bigger dimension
print(np.stack((a,b),axis = 0))

[[1 2 3 4]
 [5 6 7 8]]


In [75]:
print(np.stack((a,b),axis = 1))

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


### Reshaping a Numpy Array

In [80]:
a = np.array([
    [1,2],
    [3,4],
    [5,6],
    [7,8],
    [9,10],
    [11,12]
])
a = a.reshape((3,4)) #Therefore it will sort the array, and then reshape it into a 3x4 Matrix
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [81]:
print(a.reshape(2,6))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [83]:
#For example, we don't know. How much elements are there in the numpy array. But all we know is after reshaping
#it should have 6 columns. Then we can put -1 on row side
print(a.reshape(-1,6))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


## Mathematical Operatios like additon, subtraction,matrix multiplication,etc

In [39]:
x = np.array([
    [1,2],
    [3,4]
])
y = np.array([
    [5,6],
    [7,8]
])

In [47]:
#Element wise addition
print(x+y)

print()

#We can also perform the addition operation like this ->
print(np.add(x,y))

[[ 6  8]
 [10 12]]

[[ 6  8]
 [10 12]]


In [48]:
#Element wise subtraction
print(x-y)

print()

#We can also perform the subtraction operation like this ->
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]

[[-4 -4]
 [-4 -4]]


In [49]:
#Element wise multiplication
print(x*y)

print()

#We can also perform the mulitplication operation like this ->
print(np.multiply(x,ykm,

[[ 5 12]
 [21 32]]

[[ 5 12]
 [21 32]]


In [51]:
#Element wise dvision
print(x/y)

print()

#We can also perform the division operation like this ->
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [45]:
#Now what we want is store x^5 for each element in the matrix or numpy array
print(x**5)

[[   1   32]
 [ 243 1024]]


In [52]:
#We can also store the sqrt of each element in the array like this ->
print(x**(0.5))

print()

print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]

[[1.         1.41421356]
 [1.73205081 2.        ]]


#### MATRIX MULTIPLICATION / DOT PRODUCT

In [53]:
x = np.array([
    [1,2],
    [3,4]
])
y = np.array([
    [4,5],
    [6,7]
])

In [55]:
#Dot Product is basically matrix multiplication , as we are basically making a dot product of row of 1st 
#matrix with column of 2nd matrix in matrix multiplication
print(x.dot(y))

print()

print(np.dot(x,y))#Both the syntax perform the same operations

[[16 19]
 [36 43]]

[[16 19]
 [36 43]]


In [57]:
#Therefore dot product of 2 numpy array will look like this ->
x = np.array([1,2,3])
y = np.array([4,5,6])

In [58]:
print(np.dot(x,y))
print(x.dot(y)) #32 = 1.4 + 2.5 + 3.6

32
32


## Numpy Random

#### SHUFFLE

In [89]:
a = np.arange(7) +3
print(a)
print(a.shape)

[3 4 5 6 7 8 9]
(7,)


In [92]:
np.random.shuffle(a)
print(a)

[7 9 8 4 3 6 5]


In [111]:
#Generally shuffle is used only for 1d array like above, it will be very rarely used for for 2d array
a = np.array([
    [1,2,3],
    [4,5,6]
])

#It will sort the numpy array row wise
np.random.shuffle(a)
print(a)

[[4 5 6]
 [1 2 3]]


#### RAND

In [119]:
a = np.random.rand(3,2) #here random.rand generates a numpy array of size 3x2. It initialises the array 
#with random values with all values between 0 and 1
print(a)

[[0.27647605 0.28428323]
 [0.51990684 0.06608722]
 [0.52318767 0.66000244]]


#### RANDN

In [120]:
#Randn works same as Rand i.e generates a numpy array of randomly generated numbers. But this time, randomly generated
#values are from a standard normal distribution
a = np.random.randn(2,3)
print(a)

[[ 0.53712664  1.67241761 -1.03413208]
 [ 0.48822509 -2.41550732  0.35110042]]


#### CHOICE

In [123]:
#It picks randomly a number at the random index 
a  = np.array([1,2,3,4,5,6])
print(np.random.choice(a))

5


In [124]:
#It can even pick a number randomly from a list
myList = [1,230,21,11]
print(np.random.choice(myList))

21


#### RANDINT

In [126]:
a = np.random.randint(20,50,10) #It will generate a random numpy array of size = 10 , with all elements between 20 and 50
print(a)

[23 35 24 26 22 40 31 33 30 35]


#### RANDOM

In [129]:
#All the random numbers generated in numpy are generated through pseudo random number generators. Therefore
#if we want, evertime we generate a random number, the sequence of random numbers generated should be same. Then we
#should fix the seed value of the numbers generated. So that the pattern of random numnbers generated should be same
#everytime we run our code.
np.random.seed(1)

# STATISTICAL FUNCTIONS IN NUMPY

In [133]:
a = np.array([1,2,20,-1,5])
print(np.min(a)) #It will find the minimum element(or Numpy array) in the vector(Obviously column or row matrix can be seen as a vector)
print(np.max(a)) #It will find the maximum element(or Numpy array) in the vector

-1
20


In [130]:
a = np.array([
    [1,2,3,4],
    [7,6,2,-1]
])

print(np.min(a)) #It will find the minimum element(or Numpy array) in the matrix
print(np.max(a)) #It will find the maximum element(or Numpy array) in the matrix

-1
7


In [131]:
#We can also get the minimum row wise i.e minimum in each row
print(np.min(a,axis = 1))

[ 1 -1]


In [132]:
#We can also get the minimum column wise i.e minimum in each column
print(np.min(a,axis = 0))

[ 1  2  2 -1]


#### Mean

In [134]:
b = np.array([3,1,-1,2,6])

print(np.mean(b))

2.2


In [135]:
a = np.array([
    [1,2,3,4],
    [7,6,2,-1]
])
print(np.mean(a))

3.0


In [136]:
#For a matrix, we can also calculate mean row wise or column wise like this
print(np.mean(a,axis = 0)) #Mean column wise
print(np.mean(a,axis = 1)) #Mean row wise

[4.  4.  2.5 1.5]
[2.5 3.5]


#### Median 

In [137]:
b = np.array([3,1,-1,2,6])
print(np.median(b)) # Median = Middle element aftering arranging the elements in the sorted order

2.0


In [143]:
a = np.array([
    [1,2,3,4],
    [7,6,2,-1]
])
print(np.median(a))

2.5


#### Average - (Note Average is different from mean)

In [144]:
c = np.array([1,5,2,4])
print(np.mean(c))

3.0


In [145]:
#Note average is calcualated for a numpy array with respect to Weights. Therefore average is actually a weighted mean
#Eg - let weights be
wt = np.array([5,6,10,0])
print(np.average(c,weights = wt)) #Actually average is (np.dot(c,wt)/(sizeOfc)) i.e 
#(1*5 + 6*5 + 10*2 +4*0)/(sum of weights) = 55/21

2.619047619047619


In [146]:
#If we want that average and mean should be equal, then wts should look like this
wt = np.array([1,1,1,1])
print(np.average(c,weights = wt))

3.0


In [149]:
##Calculating standard deviation
c = np.array([4,5,3,7,-1])
standardDeviation = np.std(c)
print(standardDeviation)


2.6532998322843198


In [150]:
#Actually variable = (standardDeviation)^2
print(standardDeviation**2)
#But we can directly calculate variance too->
deviation = np.var(c)
print(deviation)

7.039999999999999
7.039999999999999


## Representation of VECTORS,MATRICES in NUMPY (I have already done it above, i am just making it clear, what above arrays would be called)

#### VECTORS

In [151]:
#VECTORS CAN BE REPRESENTED IN 2 ways - (Both ways are correct. Depending on the situation, one of them will be 
#used)
print('Method 1')
myVector = np.array([1,2,3,4])
print(myVector)
print(myVector.shape)

print('Method 2')
myVector = np.array([[1],[2],[3],[4]])
print(myVector)
print(myVector.shape)

Method 1
[1 2 3 4]
(4,)
Method 2
[[1]
 [2]
 [3]
 [4]]
(4, 1)


#### MATRICES AND TENSORS

In [157]:
## As discussed , 1d array is a vector
#2D array will be a matrix and more than 2d array will be a tensor

#Matrix
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [158]:
#Tensor
tensor = np.array([
    [[1,2],[3,4],[5,6]],
    [[7,8],[9,10],[11,12]],
    [[13,14],[15,16],[17,18]]
])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [159]:
print(matrix.shape)
print(tensor.shape)

(3, 3)
(3, 3, 2)


In [161]:
#Calualating transpose of a matrix
print(matrix)
transpose = np.transpose(matrix)
print('TRANSPOSE')
print(transpose)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
TRANSPOSE
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [163]:
#Transpose of a vector
myVector1 = np.array([[1],[2],[3],[4]])
print(myVector1)
#Therefore transpose of a vector(in above form) converts it into a row of matrix 
print(np.transpose(myVector1))

[[1]
 [2]
 [3]
 [4]]
[[1 2 3 4]]


In [168]:
## ADDITION of scalar to the matrix -
print(matrix)
print(matrix + 10) #It will add 10 to each element in the matrix


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [169]:
## Multiplication of scalar to the matrix -
print(matrix)
print(matrix*10) #It will multiply each element of the matrix to 10

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


## Norms of Vectors

In [170]:
x = np.array([-5,3,10])

In [172]:
lp1Norm = np.linalg.norm(x,ord = 1) #order =1 means L1 norm
print(lp1Norm)

18.0


In [173]:
lp2Norm = np.linalg.norm(x,ord = 2) #order =2 means L2 norm
print(lp2Norm)

11.575836902790225


In [174]:
lpInfinityNorm = np.linalg.norm(x,ord = np.inf) 
print(lpInfinityNorm)

10.0


In [176]:
x = np.array([
    [2,-2,1],
    [-1,2,-1],
    [2,-4,1]
])

print(np.linalg.norm(x,ord = np.inf))
print(np.linalg.norm(x,ord = 2))

7.0
5.9287221489704836


In [178]:
a = np.array([
    [1,-3,4],
    [-2,10,-7],
    [0,1,0],
    [0,0,0]
])

b = np.array([
    [5,0],
    [-2,11],
    [-3,12]
])
print(a.dot(b))

[[-1 15]
 [-9 26]
 [-2 11]
 [ 0  0]]


In [ ]:
#